### ISSUE TITLE
Whitspace handling broken

### ISSUE THREAD

**Issue by xi** [WhatSock/w3c-alternative-text-computation#2]
The sample implementation adds and removes whitespace,which it shouldn't. Example: The test cases contained in the repository should output the following name:

```
My name is Garaventa the weird. (QED) Where are my marbles?
```

This is the actual result:

```
My name is Garaventa the weird. ( Q E D ) Where are my marbles?
```

**Comment by accdc** [comment]
I see what you mean.

 

It does need to convert new line characters into spaces however, because newline chars aren’t supported in a flat string name computation, which was something Chrome had to fix some years back due to accessibility issues encountered resulting from this.

 

What about differing element types? E.G If you have a CSS pseudo before and after element plus an embedded IMG with an alt between static text elements? Do you think that all of these should be concatenated together with no white space between them?

**Comment by xi** [comment]
> What about differing element types? E.G If you have a CSS pseudo before and after element plus an embedded IMG with an alt between static text elements? Do you think that all of these should be concatenated together with no white space between them?


I am not exactly sure which version of the spec this is build on. In the [current working draft](https://www.w3.org/TR/accname-aam-1.1/#step2F.ii) it is clearly stated that content from CSS pseudo classes should be prepended/appended without a space.

**Comment by accdc** [comment]
This should be based on the spec at

http://www.w3.org/TR/accname-aam-1.1/

 

I’ve already raised this as an issue with the ARIA WG since it appears to directly contradict the following statement in the naming computation algorithm:

 

"Append the result of each step above, with a space, to the total accumulated text."
