### ISSUE TITLE
Nested labels are ignored

### ISSUE THREAD

**Issue by xi** [WhatSock/w3c-alternative-text-computation#4]
In HTML there are two ways to associate a label with an input element:

```
<label>
  Wrapped
  <input>
</label>

<label for="foo">
  Via ID
</label>
<input id="foo">
```

Only the latter is handled correctly.

**Comment by accdc** [comment]
Hi,

Excellent point! I’ll add this to my todo list to implement soon.

 

Please let me know if you would prefer to make this change along with the refactoring.

**Comment by accdc** [comment]
Hi, with the recent rewrite, implicit labels are now computed along with everything else, so this issue is now fixed. There is still debate on the ARIA WG about how multiple labels should be handled, but this is a separate issue and when I have a definitive answer I'll push the update to handle that as well.

**Comment by xi** [comment]
Thanks for addressing this!
