### ISSUE TITLE
Verify expectations of the "Name checkbox-label-embedded-listbox" test case

### ISSUE THREAD

**Issue by joanmarie** [WhatSock/w3c-alternative-text-computation#8]
The [expected result of the "Name checkbox-label-embedded-listbox" test case](https://whatsock.github.io/w3c-alternative-text-computation//Proposed%20Name%20and%20Description%20Tests/Name%20checkbox-label-embedded-listbox.html) is "Flash the screen 1 times." I think this might be incorrect, given the language in AccName. We need to verify it and either update the test case or change the language of the spec.

I assume that the rationale for including the "1" in the calculation is that it is the selected option. But the AccName spec's step 2E states, "If the embedded control has role combobox, return the text alternative of the chosen option." In this test case, the role is listbox; not combobox. And none of the other items in 2E seem to cover this case.

**Comment by accdc** [comment]
I remember when I coded this, and the spec text only refers to controls that support a value, but this is very vague and can be interpreted many different ways. For example, as I did when coding this, if standard form fields support explicit values, then these need to be returned, even native select elements. If this is true, then simulated ARIA widgets that map to similar constructs in the accessibility API need to also return selected values, which covers several different types of control groupings, such as range controls that support explicit value properties, or selectable widgets that include selectable children controlled using aria-selected, and so on.

An  example of this scenario is computing the name of a heading that states as embedded text "Date for departure" plus an embedded ARIA Listbox that includes the aria-selected option "May 3, 2018", in which case you only want the text plus the selected option to be conveyed as the name of the heading.

I agree this is complicated, and if we ignore it and leave this out it will be misleading because the naming computation does not state that only the value of objects that are not ARIA widget roles should be included in this step.

This is what I currently have within the AccName executable to handle this:


				// Otherwise, if the current node is non-presentational and is a nested widget control within the parent ref obj, then add only its value and process no deeper
				if (!rolePresentation && isSeparatChildFormField) {

					// Prevent the referencing node from having its value included in the case of form control labels that contain the element with focus.
					if (!(nodesToIgnoreValues && nodesToIgnoreValues.length && nodesToIgnoreValues.indexOf(node) !== -1)) {

						if (isSimulatedFormField && ['scrollbar', 'slider', 'spinbutton'].indexOf(nRole) !== -1) {
							// For range widgets, append aria-valuetext if non-empty, or aria-valuenow if non-empty, or node.value if applicable.
							name = getObjectValue(nRole, node, true);
						}
						else if (isSimulatedFormField && ['searchbox', 'textbox'].indexOf(nRole) !== -1) {
							// For simulated edit widgets, append text from content if applicable, or node.value if applicable.
							name = getObjectValue(nRole, node, false, true);
						}
						else if (isSimulatedFormField && ['grid', 'listbox', 'tablist', 'tree', 'treegrid'].indexOf(nRole) !== -1) {
							// For simulated select widgets, append same naming computation algorithm for all child nodes including aria-selected="true" separated by a space when multiple.
							// Also filter nodes so that only valid child roles of relevant parent role that include aria-selected="true" are included.
							name = getObjectValue(nRole, node, false, false, true);
						}
						else if (isNativeFormField && ['input', 'textarea'].indexOf(nTag) !== -1) {
							// For native edit fields, append node.value when applicable.
							name = getObjectValue(nRole, node, false, false, false, true);
						}
						else if (isNativeFormField && nTag === 'select') {
							// For native select fields, get text from content for all options with selected attribute separated by a space when multiple.
							name = getObjectValue(nRole, node, false, false, true, true);
						}

**Comment by joanmarie** [comment]
Conclusion: File issue against spec because listbox should be handled like combobox.

**Comment by joanmarie** [comment]
Closing this issue as being moved to https://github.com/w3c/accname/issues/12.
